### ISSUE TITLE
How to pick specific .env file?

### ISSUE THREAD

**Issue by Konnor5092** [andrewmclagan/react-env#61]
I've read the documentation and looked at the example CRA app but I can't figure out how to pinpoint a specific .env file.

I have a brand new CRA with the following file/folder structre

![image](https://user-images.githubusercontent.com/18048889/117327408-78c79e00-ae8a-11eb-92ac-282610ab708d.png)

I then updated my `package.json` with the following...

```json
  "scripts": {
    "start": "react-env --env staging -- react-scripts start"
```

I was expecting this to point to my `.env.staging` file when doing `npm start` but it doesn't. Instead it just loads the `.env` file.

I also tried `react-env --env APP_ENV=staging -- react-scripts start` but it didn't work either. 

Where am I going wrong here?

This is the output from my `npm start`

```
$ npm start

> reactenvtest@0.1.0 start E:\Repos\ReactEnvTest\reactenvtest
> react-env --env staging

Writing runtime env  E:\Repos\ReactEnvTest\reactenvtest/public/__ENV.js
{
  "REACT_APP_CRA": "Create React App",
  "REACT_APP_NEXT": "Next.js",
  "REACT_APP_NOT_SECRET_CODE": "1234"
}
```

And this is the contents of my `env.staging`

```
REACT_APP_NEXT="Staging Next.js"
REACT_APP_CRA="Staging Create React App"
REACT_APP_NOT_SECRET_CODE="12345"
```

**Comment by andrewmclagan** [comment]
To read in a specific file via an argument you would use the `--path` flag e.g. to read in .env.staging

```bash
react-env --path staging 
```

You are using the `--env` flag which looks for an existing environment variable by that name and then finds the env file from that name. e.g. `APP_ENV=production` along with `--env APP_ENV` would load `.env.production`

**Comment by bb-in-hoodie** [comment]
@andrewmclagan , 
it would be better if you make it clear that we should set `APP_ENV` as an environment variable in terminal.

![image](https://user-images.githubusercontent.com/12558317/148345254-3149bdfd-8293-4892-850f-f787f58c640d.png)

because for now with the example you've written, we might be confused as "you have to replace 'APP_ENV' with the name of environment you want". (As a result, we might end up writing `react-env --env staging` instead of `APP_ENV=staging react-env --env APP_ENV`.)
